name: Browserless Bot Runner

on:
  schedule:
    # سيقوم بتشغيل الكود كل 5 دقائق (أقصى سرعة مجانية)
    - cron: '*/5 * * * *'
  workflow_dispatch: # يتيح لك تشغيله يدوياً أيضاً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: ignore/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        env:
          # إذا أردت وضع مفاتيحك بشكل آمن (اختياري)
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: python main.py
